// SPDX-License-Identifier: MIT OR Unlicense
// Autogenerated using the Scaffold feature in wawa.Editors.
// Code generated by wawa.Editors is in public domain.
// Source: https://github.com/Emik03/wawa

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using UnityEngine;
using wawa.Modules;
using Random = UnityEngine.Random;

/// <summary>On the Subject of <see cref="LightsOut3D"/>.</summary>
public sealed class LightsOut3D : ModdedModule
{
    public Material[] ButtonMaterials;
    public GameObject[] Buttons;

    private bool[,,] buttonsActivated = new bool[3, 3, 3];
    private GameObject[,,] buttonsGrid = new GameObject[3, 3, 3];
    // Stores the current solution to solve the board state at any point
    List<string> optimalSolution = new List<string>();

    protected override void OnActivate()
    {
        int i = 0;

        foreach (GameObject button in Buttons)
        {
            button.GetComponentInChildren<KMSelectable>().OnInteract += delegate ()
            {
                ButtonInteract(button);
                return false;
            };

            buttonsGrid[ExpandTo3D(i, 0), ExpandTo3D(i, 1), ExpandTo3D(i, 2)] = button;
            i++;
        }
        foreach (GameObject button in buttonsGrid)
        {
            int index = Array.IndexOf(Buttons, button);
            if (Random.Range(0, 2) == 0)
            {
                ToggleAdjacentButtons(button, ExpandTo3D(index, 0), ExpandTo3D(index, 1), ExpandTo3D(index, 2));
            }
        }
        if (buttonsActivated.Cast<bool>().All(x => x == false))
        {
            int one = Random.Range(0, 27);
            ToggleAdjacentButtons(Buttons[one], ExpandTo3D(one, 0), ExpandTo3D(one, 1), ExpandTo3D(one, 2));
        }

        string[] boardLayout = buttonsActivated.Cast<bool>().Select(x => x ? "1" : "0").ToArray();
        Log($"The initial board state is:");
        Log("Top layer: " +
            $"{String.Join("", boardLayout, 0, 3)}/" +
            $"{String.Join("", boardLayout, 3, 3)}/" +
            $"{String.Join("", boardLayout, 6, 3)}");
        Log("Middle layer: " +
            $"{String.Join("", boardLayout, 9, 3)}/" +
            $"{String.Join("", boardLayout, 12, 3)}/" +
            $"{String.Join("", boardLayout, 15, 3)}");
        Log("Bottom layer: " +
            $"{String.Join("", boardLayout, 18, 3)}/" +
            $"{String.Join("", boardLayout, 21, 3)}/" +
            $"{String.Join("", boardLayout, 24, 3)}");

        Log($"The most optimal solution for the initial board state is, in the format \"(xyz)\" where x is" +
            $" the layer from left-right, y is the row from top-bottom, and z is the column from left-right:");

        Log($"({optimalSolution.Join(") (")})");
    }

    private void ButtonInteract(GameObject button)
    {
        int index = Array.IndexOf(Buttons, button);
        Play(Sound.ButtonPress);
        StartCoroutine(ButtonAnimation(button.transform, index));
        ToggleAdjacentButtons(button, ExpandTo3D(index, 0), ExpandTo3D(index, 1), ExpandTo3D(index, 2));
    }

    private void ToggleAdjacentButtons(GameObject button, int x, int y, int z)
    {
        string currentCommand = x.ToString() + y.ToString() + z.ToString();
        // Solutions are just an XOR of the original solution and any subsequent moves
        if (!optimalSolution.Contains(currentCommand))
        {
            optimalSolution.Add(currentCommand);
        }
        else
        {
            optimalSolution.Remove(currentCommand);
        }
        // Toggle the selected button
        ToggleButton(button, x, y, z);
        // Toggle buttons on the same row
        if (z - 1 >= 0)
        {
            ToggleButton(buttonsGrid[x, y, z - 1], x, y, z - 1);
        }
        if (z + 1 <= 2)
        {
            ToggleButton(buttonsGrid[x, y, z + 1], x, y, z + 1);
        }
        // Toggle buttons in the same column
        if (y - 1 >= 0)
        {
            ToggleButton(buttonsGrid[x, y - 1, z], x, y - 1, z);
        }
        if (y + 1 <= 2)
        {
            ToggleButton(buttonsGrid[x, y + 1, z], x, y + 1, z);
        }
        // Toggle buttons in the same position on other layers
        if (x - 1 >= 0)
        {
            ToggleButton(buttonsGrid[x - 1, y, z], x - 1, y, z);
        }
        if (x + 1 <= 2)
        {
            ToggleButton(buttonsGrid[x + 1, y, z], x + 1, y, z);
        }
    }

    private void ToggleButton(GameObject button, int x, int y, int z)
    {
        buttonsActivated[x, y, z] = !buttonsActivated[x, y, z];
        button.GetComponent<Renderer>().material = ButtonMaterials[buttonsActivated[x, y, z] ? 1 : 0];
        StartCoroutine(LightAnimation(button.transform.Find("LightQuad").transform, FlattenTo2D(x, y, z), buttonsActivated[x, y, z]));
        if (buttonsActivated.Cast<bool>().All(i => i == false))
        {
            Solve("All lights were turned off. Module solved!");
        }
    }

    private IEnumerator ButtonAnimation(Transform button, int index)
    {
        Vector3 defaultPosition = button.localPosition;
        for (int i = 0; i < 5; i++)
        {
            button.localPosition += (Vector3.down * 0.006f) / 5;
            yield return new WaitForSeconds(0.01f);
        }
        button.localPosition = defaultPosition + (Vector3.down * 0.006f);
        for (int i = 0; i < 5; i++)
        {
            button.localPosition -= Vector3.down * 0.006f / 5;
            yield return new WaitForSeconds(0.01f);
        }
        button.localPosition = defaultPosition;
        
    }

    private IEnumerator LightAnimation(Transform light, int index, bool activated)
    {
        for (int i = 0; i < 15; i++)
        {
            light.localScale += Vector3.one * (activated ? 7 : -7) / 15;
            yield return new WaitForSeconds(0.01f);
        }
        light.localScale = activated ? Vector3.one * 7 : Vector3.zero;
    }

    private int ExpandTo3D(int index, int dimension)
    {
        int i = 0;

        switch (dimension)
        {
            case 0:
                i = index / 9;
                break;
            case 1:
                i = (index / 3) % 3;
                break;
            case 2:
                i = index % 3;
                break;
            default:
                i = -1;
                break;
        }

        return i;
    }

    private int FlattenTo2D(int x, int y, int z)
    {
        return (x * 9) + (y * 3) + z;
    }

#pragma warning disable 414
    private readonly string TwitchHelpMessage = @"Press buttons using !{0} 012. Chain button presses using spaces. Each button is represented using zero-indexed numbers in the format xyz, where x is the layer from left-right, y is the row from top-bottom, and z is the column from left-right.";
#pragma warning restore 414

    IEnumerator ProcessTwitchCommand(string command)
    {
        command = command.Trim().ToLower();
        yield return null;
        string[] commands = command.Split(' ');
        for (int i = 0; i < commands.Length; i++)
        {
            if (!Regex.IsMatch(commands[i], @"^[0-2]{3}$"))
            {
                yield return "sendtochaterror Each button press must be separated by spaces and contain exactly three numbers from 0-2.";
                yield break;
            }
        }
        for (int i = 0; i < commands.Length; i++)
        {
            buttonsGrid[int.Parse(commands[i][0].ToString()), int.Parse(commands[i][1].ToString()), int.Parse(commands[i][2].ToString())].GetComponentInChildren<KMSelectable>().OnInteract();
            yield return new WaitForSeconds(.1f);
        }
    }

    IEnumerator TwitchHandleForcedSolve()
    {
        string[] finalCommands = optimalSolution
            .OrderBy(g => Random.Range(0, 1000))
            .ToArray();
        foreach (string command in finalCommands)
        {
            buttonsGrid[int.Parse(command[0].ToString()), int.Parse(command[1].ToString()), int.Parse(command[2].ToString())].GetComponentInChildren<KMSelectable>().OnInteract();
            yield return new WaitForSeconds(0.1f);
        }
    }
}
